name: TEST
on:
  push:
    branches:
    - master
    paths:
    - '**.ts'
    - '**.tsx'
    - '**.js'
    - '**.cjs'
    - '**.json'
    - '.github/workflows/test.yml'
  pull_request:
    branches:
    - master
    paths:
    - '**.ts'
    - '**.tsx'
    - '**.js'
    - '**.cjs'
    - '**.json'
    - '.github/workflows/test.yml'
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts/*' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  framework-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.PREVIOUS_NODE_VERSION }}
  framework-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.CURRENT_NODE_VERSION }}
  cli-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd cli && npm ci
      - run: cd cli && npm run language
      - run: cd cli && npm run test
      - run: mv ./cli/coverage ./
      - run: sed -i 's/SF:src/SF:cli\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: cli ${{ env.PREVIOUS_NODE_VERSION }}
  cli-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd cli && npm ci
      - run: cd cli && npm run language
      - run: cd cli && npm run test
      - run: mv ./cli/coverage ./
      - run: sed -i 's/SF:src/SF:cli\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: cli ${{ env.CURRENT_NODE_VERSION }}
  framework-integration-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.PREVIOUS_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.PREVIOUS_NODE_VERSION }}
  framework-integration-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.CURRENT_NODE_VERSION }}
  documentation-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run test
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-website
  documentation-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e
  end:
    runs-on: ubuntu-latest
    needs:
      - framework-previous
      - framework-current
      - cli-previous
      - cli-current
      - framework-integration-current
      - framework-integration-previous
      - documentation-website
      - documentation-e2e
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
